version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: host
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7:7"
      - "9:9"
      - "13:13"
      - "19:19"
      - "20:20"
      - "21:21"
      - "23:23"
      - "25:25"
      - "37:37"
      - "69:69"
      - "80:80"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "2007:2007"
      - "2013:2013"
      - "2080:2080"
      - "50001:50001"  
    networks:
      - webnet
networks:
  webnet:

